from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any
from fpdf import FPDF


def _clean_citekey(title: str, year: Any, authors: list[str] | None = None) -> str:
    lead = "source"
    if authors and len(authors) > 0 and authors[0]:
        lead = re.sub(r"[^a-zA-Z]", "", authors[0].split()[-1]).lower()
    elif title:
        words = [re.sub(r"[^a-zA-Z]", "", w).lower() for w in title.split() if w]
        if words:
            lead = words[0]
    yr = str(year) if year else "2025"
    slug = re.sub(r"[^a-zA-Z0-9]", "", title[:20]).lower()
    return f"{lead}_{yr}_{slug[:10]}"


def generate_bibtex(sources: list[dict]) -> str:
    """Generate clean BibTeX bibliography for all academic and web sources."""
    entries: list[str] = []
    seen_keys: set[str] = set()

    for s in sources:
        title = s.get("title") or "Untitled Resource"
        year = s.get("year") or ""
        authors = s.get("authors") or []
        doi = s.get("doi") or ""
        url = s.get("url") or ""
        venue = s.get("venue") or ""
        source_type = s.get("source_type") or "article"

        citekey = _clean_citekey(title, year, authors)
        if citekey in seen_keys:
            citekey += f"_{len(seen_keys)}"
        seen_keys.add(citekey)

        author_str = " and ".join(authors) if authors else "ResearchMind Extracted"
        clean_title = title.replace("{", "").replace("}", "")

        if source_type == "academic":
            entry = [
                f"@article{{{citekey},",
                f"  title = {{{clean_title}}},",
                f"  author = {{{author_str}}},",
            ]
            if venue:
                entry.append(f"  journal = {{{venue}}},")
            if year:
                entry.append(f"  year = {{{year}}},")
            if doi:
                entry.append(f"  doi = {{{doi}}},")
            if url:
                entry.append(f"  url = {{{url}}},")
            entry.append("}")
        else:
            entry = [
                f"@misc{{{citekey},",
                f"  title = {{{clean_title}}},",
                f"  howpublished = {{\\url{{{url}}}}},",
                f"  note = {{Accessed via ResearchMind: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}}},",
            ]
            if year:
                entry.append(f"  year = {{{year}}},")
            entry.append("}")

        entries.append("\n".join(entry))

    return "\n\n".join(entries) if entries else "% No sources recorded for this research session."


def generate_markdown(session: dict, report: dict | None, sources: list[dict], findings: list[dict] | None = None) -> str:
    """Generate complete research export as formatted Markdown with frontmatter."""
    query = session.get("query", "Untitled Research")
    status = session.get("status", "unknown")
    created = session.get("created_at", datetime.now(timezone.utc).isoformat())

    md_lines = [
        "---",
        f"title: \"{query}\"",
        f"date: \"{created}\"",
        f"status: \"{status}\"",
        f"sources_count: {len(sources)}",
        "generated_by: \"ResearchMind Autonomous Agentic Assistant\"",
        "---",
        "",
        f"# {query}",
        "",
        "> **Executive Briefing generated by ResearchMind multi-agent orchestration.**",
        f"> *Date: {created} | Status: {status} | Sources Reviewed: {len(sources)}*",
        "",
    ]

    if report and report.get("markdown"):
        md_lines.append(report["markdown"])
    else:
        md_lines.append("## Status\nNo synthesized report generated yet.")

    # Append Sources & References
    md_lines.extend(["", "---", "", "## Verified Sources & Evidence Bibliography", ""])
    for i, s in enumerate(sources, 1):
        stype = s.get("source_type", "web").capitalize()
        title = s.get("title", "Resource")
        url = s.get("url", "#")
        score = s.get("score")
        score_txt = f" (Credibility Score: {score:.2f})" if score is not None else ""
        year = f" ({s.get('year')})" if s.get("year") else ""
        venue = f" - *{s.get('venue')}*" if s.get("venue") else ""
        md_lines.append(f"{i}. **[{title}]({url})**{year}{venue} `[{stype}]`{score_txt}")
        snippet = s.get("snippet")
        if snippet:
            md_lines.append(f"   > {snippet[:200]}...")

    return "\n".join(md_lines)


class ResearchPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "RESEARCHMIND | AUTONOMOUS AGENTIC RESEARCH BRIEFING", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def _sanitize_pdf_text(text: str) -> str:
    """Replace unsupported characters with Latin-1 equivalents for standard PDF core fonts."""
    replacements = {
        "—": "--",
        "–": "-",
        "“": "\"",
        "”": "\"",
        "‘": "'",
        "’": "'",
        "…": "...",
        "•": "*",
        "→": "->",
        "≥": ">=",
        "≤": "<=",
        "₹": "INR ",
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_pdf(session: dict, report: dict | None, sources: list[dict]) -> bytes:
    """Generate a clean, printable academic research paper PDF."""
    pdf = ResearchPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    query = _sanitize_pdf_text(session.get("query", "Research Report"))
    date_str = session.get("created_at", "")[:10]

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(25, 25, 30)
    pdf.multi_cell(0, 8, query, align="L")
    pdf.ln(3)

    # Metadata subline
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 110)
    meta_text = f"Autonomous Research Synthesis | Date: {date_str} | Verified Sources: {len(sources)}"
    pdf.cell(0, 6, _sanitize_pdf_text(meta_text), ln=True)
    pdf.set_draw_color(200, 180, 100)
    pdf.set_line_width(0.5)
    pdf.line(pdf.get_x(), pdf.get_y() + 2, 200, pdf.get_y() + 2)
    pdf.ln(6)

    # Report Body
    markdown = (report.get("markdown") if report else "") or "No report content available."
    lines = markdown.split("\n")

    for raw_line in lines:
        line = _sanitize_pdf_text(raw_line.strip())
        if not line:
            pdf.ln(2)
            continue

        if line.startswith("# "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(30, 40, 60)
            pdf.multi_cell(0, 7, line[2:])
            pdf.ln(1)
        elif line.startswith("## "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(40, 50, 70)
            pdf.multi_cell(0, 6, line[3:])
            pdf.ln(1)
        elif line.startswith("### "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(60, 70, 80)
            pdf.multi_cell(0, 5, line[4:])
        elif line.startswith("> "):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(80, 80, 90)
            pdf.multi_cell(0, 5, "    " + line[2:])
        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 5, "  * " + line[2:])
        else:
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 5, line)

    # Sources & References Section
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 40, 60)
    pdf.cell(0, 7, "References & Evidence", ln=True)
    pdf.set_font("Helvetica", "", 8.5)

    for i, s in enumerate(sources[:25], 1):
        stitle = _sanitize_pdf_text(s.get("title") or "Resource")
        surl = _sanitize_pdf_text(s.get("url") or "")
        stype = s.get("source_type", "web")
        svenue = f" ({_sanitize_pdf_text(s.get('venue'))})" if s.get("venue") else ""
        syear = f", {s.get('year')}" if s.get("year") else ""
        ref_line = f"[{i}] {stitle}{svenue}{syear} [{stype}]. {surl}"
        pdf.set_text_color(70, 70, 70)
        pdf.multi_cell(0, 4.5, ref_line)
        pdf.ln(1)

    return bytes(pdf.output())
